apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
  labels:
    app: ping
  namespace: pingpong
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping
        image: gitlab.fairmat.com:5050/fairmat/dev/infrastructure/kubernetesdemo:prod_1.2
        ports:
        - containerPort: 80
      - name: pong
        image: gitlab.fairmat.com:5050/fairmat/dev/infrastructure/kubernetesdemo:pong-prod_1.2
        ports:
        - containerPort: 80 
